### ISSUE TITLE
Error message on every startup

### ISSUE THREAD

**Issue by nyhudson** [blueman-project/blueman#639] opened 2017-01-07 20:21 UTC
I get the following error message on every startup:

"Configured directory for incoming files does not exist"

I try to open blueman-services and there are no options to change this. Actually, when I open blueman-services I get a lot of python error messages. This is really annoying behavior and I would suggest you make your software a little more user friendly!

Am using Fedora 25. Anyway, will uninstall this software.

**Comment by infirit** [comment] 2017-01-07 20:29
Unless something changed blueman is still broken in fedora, see https://github.com/blueman-project/blueman/issues/537 for some background. Closing as a dupe of #537.

**Closed by infirit** 2017-01-07 20:29 UTC

**Comment by nyhudson** [comment] 2017-01-08 19:13
Thanks for the reply. Well, then Fedora really shouldn't include blueman until it is fixed. I should go yell at Fedora devs instead :-)
