### ISSUE TITLE
AttributeError: 'PulseAudioUtils' object has no attribute 'connect_rfcomm'

### ISSUE THREAD

**Issue by nico202** [blueman-project/blueman#1192] opened 2020-03-16 09:20 UTC
Hi, when pulse audio crashes, the error in the title appears.

It seems that connect_rfcomm
https://github.com/blueman-project/blueman/blob/a0ab19f5bb6a9c4f290604960856b3f3949bcf1f/blueman/main/PulseAudioUtils.py#L213

is defined in the PPPConnection and not in PulseAudioUtils.
https://github.com/blueman-project/blueman/blob/a0ab19f5bb6a9c4f290604960856b3f3949bcf1f/blueman/main/PPPConnection.py#L123

The only other usage of the method I could find is here:
https://github.com/blueman-project/blueman/blob/a0ab19f5bb6a9c4f290604960856b3f3949bcf1f/blueman/plugins/mechanism/Ppp.py#L27

where it's called on the right object.

Maybe the right function is connect_pulseadio

https://github.com/blueman-project/blueman/blob/a0ab19f5bb6a9c4f290604960856b3f3949bcf1f/blueman/main/PulseAudioUtils.py#L362

But it's my first look at the code, so I'm not sure

Thanks, Nicolò

**Comment by nico202** [comment] 2020-03-16 09:35
Created a PR in case my guess was right

**Comment by infirit** [comment] 2020-03-16 16:18
Yeah that looks like an obvious mistake. Do you have a way to reproduce
this, just kill pulseaudio?

**Comment by nico202** [comment] 2020-03-16 16:29
Basically, yes.  My pulseaudio was dying as soon as bluetooth was opened because of a broken plugin.

**Comment by infirit** [comment] 2020-04-08 18:51
Fix was merged, closing

**Closed by infirit** 2020-04-08 18:51 UTC
