### ISSUE TITLE
Bluman 2.3: a NewStatus signal is sent with a null parameter (status), which should not happen

### ISSUE THREAD

**Issue by birdie-github** [blueman-project/blueman#1782] opened 2022-07-15 12:44 UTC
blueman: 2.3-1.fc36.x86_64
BlueZ: bluez-5.64-1.fc36.x86_64
Distribution: Fedora 36
Desktop environment: XFCE

[crash.txt](https://github.com/blueman-project/blueman/files/9120814/crash.txt)

As soon as my BT headphones connect, there's a segfault in the XFCE panel and after that it's impossible to use it (keeps showing the busy cursor while mouse hovering it, the bluman systray icon completely disappears - restarting `/usr/bin/python3 /bin/blueman-applet` and `/usr/bin/python3 /usr/bin/blueman-tray` does **not** help). I've tried restarting the panel: `xfce4-panel -r`, also I've tried `killall xfce4-panel` and starting it again - nothing helps.

I know this is probably not the right place to file this bug report but XFCE is in semi-alive state right now, so it may take them forever to fix this bug report, so I'm pestering you instead.

It seems like there's something you're doing which is _incompatible_ with XFCE's system tray implementation.

Reverting to blueman-2.2.5-1.fc36.x86_64 fixes the issue. It's near impossible to find on mirrors but if people need it, here it is:

[blueman-2.2.5-1.fc36.x86_64.rpm](https://github.com/blueman-project/blueman/files/9121035/blueman-2.2.5-1.fc36.x86_64.zip)

**Comment by birdie-github** [comment] 2022-07-15 18:06
An XFCE developer, Gaël Bonithon, says Blueman works incorrectly:

https://gitlab.xfce.org/xfce/xfce4-panel/-/issues/602#note_52134

**Comment by cschramm** [comment] 2022-07-15 21:38
Thanks for the report. I do get the problem but... do I need any specific version of Xfce or anything? I fail to replicate it with 4.16 on Debian. :thinking:

**Comment by birdie-github** [comment] 2022-07-15 22:26
> Thanks for the report. I do get the problem but... do I need any specific version of Xfce or anything? I fail to replicate it with 4.16 on Debian.

I'm not sure why you're not hitting it, I'm running Fedora 36 and it's reproducible 100% of the time. Maybe the XFCE developer could explain what's incorrect in your code.

**Comment by infirit** [comment] 2022-07-15 22:38
Sure, the status string is missing but then the xfce statusnotifier/notification applet should check it got a proper string and not crash.

@cschramm I can't reproduce this on Arch under XFCE 4.16.3 and KDE Plasma 5.25.3.

**Comment by Tamaranch** [comment] 2022-07-16 06:56
Yes, it's true that we do this check for all the other signals: nullity of the GVariant then conformity of the format. I will add this check also for "NewStatus" which is treated separately in our code.
However, this will generate a warning (as it would for the other signals), because there is a data format issue: `()` instead of `(s)`.

**Comment by cschramm** [comment] 2022-07-16 06:57
A fix is in #1785 but I cannot test as nothing fails for me in xfce4-panel 4.16.4. :shrug:

**Comment by Tamaranch** [comment] 2022-07-16 07:03
It may be necessary to enable/disable bluetooth via the status notifier menu. You must then get at least some critical warnings of this type:
```
(wrapper-2.0:18971): GLib-CRITICAL **: 09:00:51.403: the GVariant format string '(s)' has a type of '(s)' but the given value has a type of '()'

(wrapper-2.0:18971): GLib-CRITICAL **: 09:00:51.403: g_variant_get: assertion 'valid_format_string (format_string, TRUE, value)' failed
```

**Comment by cschramm** [comment] 2022-07-16 07:31
Hm, weird. I just downgraded GLib to check if error handling changed on that layer and it actually started to crash but it also still crashes now after going back to the newer version (2.72.3). :thinking:

**Closed** 2022-07-16 07:32 UTC
