### ISSUE TITLE
[Feature Request]Add option to never show the tray icon / indicator

### ISSUE THREAD

**Issue by FreaxMATE** [blueman-project/blueman#1689] opened 2022-03-12 21:14 UTC
If you are using the Ayatana bluetooth indicator you do not want the blueman app indicator to always appear when you turn on the bluetooth. So an option (gsettings key) to never show the tray/indicator icon would be helpful.

**Comment by cschramm** [comment] 2022-03-13 06:08
This is duplicate of #1495. You're welcome to check #1496 that makes the StatusIcon plugin unloadable.

**Closed by cschramm** 2022-03-13 06:08 UTC
