### ISSUE TITLE
Bluetooth Group Network automatic connection inconsistent

### ISSUE THREAD

**Issue by rhyek** [blueman-project/blueman#1466] opened 2020-12-13 03:30 UTC
blueman: 2.1.3-2ubuntu1.1
BlueZ: ?
Distribution: Lubuntu 20.10
Desktop environment: LXDE/LXQT

* [x] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

I believe the intended functionality for blueman so far is generally fine, but I have a question regarding my specific use case:

I have a new mini-pc that I intend to sometimes carry around during travel for development purposes mostly. It will be used mostly in a headless manner without any peripherals or monitor connected to it. I also carry around a MacBook Pro and what I need is for the mini-pc to reliably connect to the internet via a tether to my MacBook's bluetooth where I have "Internet Sharing" turned on.

With monitor and peripherals connected to the mini-pc, once the bluetooth is connected I can right click on my MPB device in the device list in blueman, then click on "Group Network" below "Connect:". This works great and internet works. The problem is that the connection to that network is not reliably recovered in cases such as rebooting the mini-pc, turning the bluetooth off and then on on the MBP (with or without disabling Internet Sharing beforehand), though it always reconnects to the network if I just disable/enable Internet Sharing on the MBP while the bluetooth is connected and remains so.

When the connection is not re-enabled in one of these cases, no amount of turning off/on the bluetooth or connecting and disconnecting on the MBP will trigger the "Connect to: Group Network" on the mini-pc and I have to do it manually somehow.

Can anything be done about this? Maybe a script that runs automatically when the bluetooth connects where I can trigger the connection manually via some command?

Thanks!

**Comment by cschramm** [comment] 2020-12-13 09:29
Duplicate of #239. There is an auto-connect "backend" in the current master (#853) and a pull request for the frontend parts in #1414.

**Closed by cschramm** 2020-12-13 09:29 UTC

**Comment by rhyek** [comment] 2020-12-13 20:07
@cschramm thank you for responding. I'll write this here as I don't want to pollute the linked issues.

I am not very familiar with this project, but I managed to somewhat install from source successfully so I could have the autoconnect plugin. After `make install` I was running into a few issues that I guess just had to do with a mismatched desktop environment or distro to your development environment (like the blueman module install location and others). I had given up and just ran `sudo apt install blueman`, but noticed the plugin was now available! So I guess I have it running.

Anyways, the autoconnect plugin seems to work for the most part. It consistently reconnects to the Group Network service (shared internet) when running a power cycle on the minipc, but disabling bluetooth on my MBP for ~20s, then reenabling it works, but it takes around 4m 30s and not the 60s mentioned in the plugin description. I tested this twice. In these cases I find it is better for me to do a power cycle on the mini pc and have the auto reconnect work immediately.

**Comment by cschramm** [comment] 2020-12-14 08:19
The plugin currently tries to auto-connect on start and every minute (as there's no good way to get to know when the remote device becomes available).

It would make perfect sense to also try it when an adapter becomes available, yes.

Regarding the 4, 5 minutes it takes after re-enabling Bluetooth: Can you please provide the debug output of blueman-applet for that?
