### ISSUE TITLE
Key binding to quit app, like Ctrl+Q

### ISSUE THREAD

**Issue by megatux** [blueman-project/blueman#1429] opened 2020-11-06 14:58 UTC
It would be nice to have this key binding, to work similar to other setup utilities on the distro and feel more integrated.

blueman: 2.1.3
Distribution: Manjaro
Desktop environment: I3

* [X] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

**Comment by cschramm** [comment] 2020-11-06 15:11
Duplicate of #1045, #1406 is in master.

**Closed by cschramm** 2020-11-06 15:11 UTC
