### ISSUE TITLE
Connection Failed: No such file or directory

### ISSUE THREAD

**Issue by DarkKnight290** [blueman-project/blueman#833] opened 2018-01-31 02:55 UTC
blueman:
BlueZ:
Distribution:
Desktop environment:

* [x] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

> ℹ Please use some service like [Pastebin](http://pastebin.com/) or [GitHub Gist](https://gist.github.com/) to post your logs and keep the thread clean and readable. Make sure to describe the exact steps you took when producing it.

**Comment by infirit** [comment] 2018-02-03 20:51
Closing as duplicate of #830. All the info you need to fix this is in there. If you still have problems report back here with proper info as described in https://github.com/blueman-project/blueman/wiki/Troubleshooting

**Closed by infirit** 2018-02-03 20:51 UTC
Labels: needinfo
