### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by jbierkens** [blueman-project/blueman#1517] opened 2021-04-02 20:37 UTC
If I right click in the bluetooth manager tray icon, I get a useful menu. There is one feature I often use which isn't in the menu however: to disconnect currently connected bluetooth device. Is it possible to add this? (Also there are many items in the menu that I never use, in fact I only use the "Recent connections" and "Devices..." menu items, to connect and disconnect.)

blueman: 2.12
BlueZ:
Distribution: Xubuntu 20.04.2
Desktop environment: XFCE

**Comment by cschramm** [comment] 2021-05-06 22:33
Duplicate of #1268, added in #1427.

**Closed** 2021-05-06 22:33 UTC
