### ISSUE TITLE
Raspberry 4B how auto-connect Bluetooth device on setup

### ISSUE THREAD

**Issue by lixunhui** [blueman-project/blueman#1462] opened 2020-12-09 10:12 UTC
blueman:2.0.8
BlueZ:5.5
Distribution:Raspberry4B can't connect bluetooth device ,but It can be connect by blueman-applet;
![image](https://user-images.githubusercontent.com/4917509/101615697-649d8300-3a49-11eb-9d24-159ed71ec5e4.png)

use system bluetooth 
![image](https://user-images.githubusercontent.com/4917509/101615802-84cd4200-3a49-11eb-9254-cddfad385a49.png)

use blueman 
![image](https://user-images.githubusercontent.com/4917509/101615869-99a9d580-3a49-11eb-939d-3d5285b8f12f.png)
![image](https://user-images.githubusercontent.com/4917509/101615917-ab8b7880-3a49-11eb-9f98-15d15f725051.png)
![image](https://user-images.githubusercontent.com/4917509/101615950-b80fd100-3a49-11eb-9ba3-349d04d3f288.png)
![image](https://user-images.githubusercontent.com/4917509/101616153-f86f4f00-3a49-11eb-9df4-a57c69ac19a1.png)

**how can I auto-connect this device on System setup**

**Comment by cschramm** [comment] 2020-12-09 11:05
Duplicate of #239. There is an auto-connect "backend" in the current master (#853) and a pull request for the frontend parts in #1414.

**Closed by cschramm** 2020-12-09 11:05 UTC
