### ISSUE TITLE
Blueman can't find devices near me, while hcitool scan can

### ISSUE THREAD

**Issue by N0rbert** [blueman-project/blueman#1621] opened 2021-10-24 13:43 UTC
blueman: 2.2.2 from https://packages.ubuntu.com/impish/blueman
BlueZ: 5.60 from https://packages.ubuntu.com/impish/bluez
Distribution: Ubuntu MATE 21.10
Desktop environment: MATE 1.26.0

* [x] I have consulted the [Troubleshooting page](https://github.com/blueman-project/blueman/wiki/Troubleshooting) and done my best effort to follow.

Steps to reproduce:
1. Enable two my personal Bluetooth devices - Logitech M555b Mouse and SVEN bluetooth speaker, make both discoverable
2. Open terminal and launch `hcitool scan`:
```
$ hcitool scan
Scanning ...
 A0:E9:DB:20:FF:FF SVEN PS-100BL
 00:07:61:FD:FF:FF Logitech Bluetooth Mouse M555b
```

3. From the same terminal execute `blueman-manager` to get the same devices in GUI, to pair with them

Expected results:
* blueman-manager finds my devices, pair with them

Actual results:
* blueman-manager does not find my devices, shows error in terminal

```
$ blueman-manager
blueman-manager 16.17.35 ERROR Base:85 callback : Unhandled error for org.bluez.Adapter1.StopDiscovery
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/blueman/bluez/Base.py", line 78, in callback
    value = proxy.call_finish(result).unpack()
gi.repository.GLib.GError: g-io-error-quark: GDBus.Error:org.bluez.Error.InProgress: Operation already in progress (36)
```

ProblemType: Bug
DistroRelease: Ubuntu 21.10
Package: blueman 2.2.2-1
ProcVersionSignature: Ubuntu 5.13.0-20.20-generic 5.13.14
Uname: Linux 5.13.0-20-generic x86_64
ApportVersion: 2.20.11-0ubuntu70
Architecture: amd64
CasperMD5CheckResult: pass
CurrentDesktop: MATE
Date: Sun Oct 24 16:16:05 2021
InstallationDate: Installed on 2021-10-24 (0 days ago)
InstallationMedia: Ubuntu-MATE 21.10 "Impish Indri" - Release amd64 (20211012)
SourcePackage: blueman
UpgradeStatus: No upgrade log present (probably fresh install)

Downstream bug-report is at https://bugs.launchpad.net/blueman/+bug/1948582 .

**Comment by infirit** [comment] 2021-11-10 21:41
Do you have another bluetooth manager running like bluedevil or gnome-bluetooth?

Basically, blueman tries to end discovery but for some reason something else already started this. Post the log of `blueman-applet --loglevel debug` which contains your pair attempt.

**Comment by N0rbert** [comment] 2021-11-11 10:06
Thank you for reply!

No, I do not use any other bluetooth manager. It is fresh Ubuntu MATE 21.10 installation. Also happens on Live media.
See log from it [blueman.txt](https://github.com/blueman-project/blueman/files/7519500/blueman.txt).

I supposed that it maybe kernel/drivers issue, so I tried bluedevil and gnome-bluetooth on the same hardware and they work normally.

Our users are very dissapointed by broken bluetooth. Examples:

* [1948582 – Blueman can't find devices near me, while hcitool scan can](https://pad.lv/1948582)
* [1945043 – Impish: problem with bluetooth mouse: not connectable](https://pad.lv/1945043)
* [1943813 – Problem with bluetooth keyboard: not usable in MATE](https://pad.lv/1943813)

Could you please install Ubuntu MATE 21.10 to some your laptop and test this issue to find real root of the problem?

**Comment by N0rbert** [comment] 2021-11-11 19:20
Right, and Blueman window is empty. Thank you for cooperation.

**Comment by infirit** [comment] 2021-11-11 20:03
I installed 21.10 in a VM and none of my usb dongles (BT 4 and 5) show this behaviour. I'll look into making the a patch to at least handle it gracefully but if we can't reproduce this it's really hard to fix

**Comment by infirit** [comment] 2021-11-11 20:42
The best thing to do is see if there are errors in the journal for bluetooth.

`journalctl -r -u bluetooth`

**Comment by N0rbert** [comment] 2021-11-12 12:09
After long trial-and-error path I got my SVEN speaker paired and connected, but Logitech mouse is not found by Blueman at all.
I tried to prepare a screencast using old Lenovo SL500 with Lenovo SL500 with Broadcom BCM2045B

![bluetooth](https://user-images.githubusercontent.com/309456/141464073-99148630-d176-4758-9a88-25b4155d12a8.gif)

(here B866 is not my device, seems to be neighbor's) and archived the whole `/var/log` folder -  [var-log.tar.gz](https://github.com/blueman-project/blueman/files/7527385/var-log.tar.gz) .

Will test again with Asustek UX32 and its [Intel 6235](https://www.intel.com/content/dam/www/public/us/en/documents/product-briefs/centrino-advanced-n-6235-brief.pdf) with Bluetooth.

**Comment by infirit** [comment] 2021-11-12 16:26
There is no point posting everything in /var/log. Just check and post the logs requested, more is just noise.

And you don't have repeat that scanning with hcitool it shows up. This is several levels down in the bluetooth stack that we do not use directly. Blueman uses the BlueZ dbus api for most things. 

I see the mouse in the applet log which is good so we get it from BlueZ's dbus api. I am confused though why you have 2 blueman-applet logs in the same file though..?

I can see that the the Alias is the btaddress and we hide these by default these days. There is an option in the menu to disable it. Disable that and look for a device name `00-07-61-FD-8F-EA`.

**Comment by N0rbert** [comment] 2021-11-14 18:09
Ok, let's start from the beginning. I have Bluetooth mouse Logitech M555b, maybe from 2009-2010 year. Thus it is probably Bluetooth 2.0. It works normally with my current daily driver system - Ubuntu MATE 18.04 LTS. 
Before it worked flawlessly on 11.04, 12.04 LTS, 14.04 LTS and 16.04 LTS. I do not remember that I need to change some sensitive defaults. So here I act as normal average user, in plug-and-play manner.
As QA tester I need to be assured that MATE and other third-party components are still working with at least my hardware, so in future I can jump to newer LTS version without a hurt.

As a note, my mouse works normally with Ubuntu MATE 20.04.3 LTS - see

![2004-success](https://user-images.githubusercontent.com/309456/141686513-d9828e8d-1f59-43b4-81a6-618ffd9e8f01.png)

[2004_blueman_--loglevel=debug.txt](https://github.com/blueman-project/blueman/files/7533983/2004_blueman_--loglevel.debug.txt)
[2004_syslog.txt](https://github.com/blueman-project/blueman/files/7533984/2004_syslog.txt)

Then after deeper analysis I determined that something weird happened, and it stopped to work in newer versions. I did more research and I see that it does not work with Ubuntu MATE 21.04 - see below:

![2104-fail](https://user-images.githubusercontent.com/309456/141686572-abaec2bf-f973-44f4-8776-58a5d5bc5508.png)

[2104_blueman-applet_--loglevel=debug.txt](https://github.com/blueman-project/blueman/files/7533988/2104_blueman-applet_--loglevel.debug.txt)
[2104_syslog.txt](https://github.com/blueman-project/blueman/files/7533989/2104_syslog.txt)

It got connected for a couple of seconds, then disconnects. Reboot, radio on/off, mouse on/off does not help. Really I do not care about this release, it will go EOL in January.

In Ubuntu MATE 21.10 the situation is even worse. I do not see my mouse in Blueman at all. While `hcitool` finds it everytime.
Setting *View → Hide unnamed devices* helped, after third or fourth attempt it is finally connected, see

![21-10-success](https://user-images.githubusercontent.com/309456/141689168-889f86e1-d4a8-4cb9-8aa8-38b0dd5fd5fa.png)

mouse is now paired, after reboot works from login Arctica Greeter screen.

But this *View → Hide unnamed devices* it is absolutely unexpected for me. 
For whom they are unnamed? Why they are unnamed? Why they were named in previous Ubuntu versions? Where should we inform our users about this new "defaults"?
My mouse has a name on its bottom, and `hcitool` says it. Who is responsible for this - Bluez or Blueman?
Could you please untick *Hide unnamed devices* for future versions?

**Comment by infirit** [comment] 2021-11-14 18:53
> But this _View → Hide unnamed devices_ it is absolutely unexpected for me. For whom they are unnamed? Why they are unnamed? Why they were named in previous Ubuntu versions? Where should we inform our users about this new "defaults"? My mouse has a name on its bottom, and `hcitool` says it. Who is responsible for this - Bluez or Blueman? Could you please untick _Hide unnamed devices_ for future versions?

You can see looking at `2104_blueman-applet_--loglevel=debug.txt` It has `Name': 'Logitech Bluetooth Mouse M555b'` and `'Alias': 'Logitech Bluetooth Mouse M555b'` which is not the case with the logs you posted for a later release where there is no `'Name'` and 'Alias': '00-07-61-FD-8F-EA',`. What BlueZ then does when there is no Name is set Alias to be the bluetooth address. Why it is unnamed in later BlueZ versions you'll have to raise with Ubuntu/BlueZ folks as this is how we get it over dbus. There is nothing blueman can do about this.

As to why it is hidden by default. Unnamed devices are everywhere and will clutter the list of devices if you are in a spot with lot's of people. We get complaints either way so I opted to handle this as most operating systems do and that is hide them. You can ask the Ubuntu MATE ppl to add a gsettings override for this if they believe it warrants one.

**Comment by cschramm** [comment] 2021-11-14 23:00
The different behavior is rather unexpected to me. Two questions on that:

Are the results for 20.04 and 21.04 for the same hardware and thus Bluetooth adapter? Otherwise the device itself might behave differently. To double-check you could have a look at `btmon`. When the device gets found, you'll see a `MGMT Event: Device Found (0x0012)` that might or might not show a `Name`.

Did / could you check 20.10 as well?

**Comment by infirit** [comment] 2021-11-15 00:03
I noticed something strange. It seems the Name/Alias is updated later these days, we handle this properly though. Because we never add the device the the managerDeviceList we don't update when the name changed.

Why we get the a proper Name/Alias after `InterfacesAdded` is weird to me.

```
/: org.freedesktop.DBus.ObjectManager.InterfacesAdded (objectpath '/org/bluez/hci0/dev_F8_77_B8_AD_50_FE', {'org.freedesktop.DBus.Introspectable': @a{sv} {}, 'org.bluez.Device1': {'Address': <'F8:77:B8:AD:50:FE'>, 'AddressType': <'public'>, 'Alias': <'F8-77-B8-AD-50-FE'>, 'Paired': <false>, 'Trusted': <false>, 'Blocked': <false>, 'LegacyPairing': <false>, 'RSSI': <int16 -96>, 'Connected': <false>, 'UUIDs': <@as []>, 'Adapter': <objectpath '/org/bluez/hci0'>, 'ManufacturerData': <{uint16 117: <[byte 0x42, 0x04, 0x01, 0x40, 0x4f, 0xf8, 0x77, 0xb8, 0xad, 0x50, 0xfe, 0xfa, 0x77, 0xb8, 0x30, 0x50, 0xfd, 0x24, 0xf9, 0x00, 0x00, 0x00, 0x00, 0x00]>}>, 'ServicesResolved': <false>}, 'org.freedesktop.DBus.Properties': {}})

/org/bluez/hci0/dev_F8_77_B8_AD_50_FE: org.freedesktop.DBus.Properties.PropertiesChanged ('org.bluez.Device1', {'TxPower': <int16 9>, 'Name': <'[TV] Samsung 5 Series (40)'>, 'Alias': <'[TV] Samsung 5 Series (40)'>}, @as [])
```

**Comment by N0rbert** [comment] 2021-11-20 18:52
> Are the results for 20.04 and 21.04 for the same hardware and thus Bluetooth adapter?
Yes, same Lenovo SL500.

> Did / could you check 20.10 as well?
Just tested Ubuntu MATE 21.10 with all updates. Mouse is found, paired and connected instantly. No specifics.

Should I manually apply and compile https://github.com/blueman-project/blueman/pull/1634 locally on Ubuntu MATE 22.04 LTS (development version)?

**Comment by cschramm** [comment] 2021-11-22 08:39
21.10 works fine?!

So we have (Ubuntu / BlueZ):
- 20.04 / 5.53: Good.
- 20.10 / 5.55: Unknown
- 21.04 / 5.56: Bad
- 21.10 / 5.60: Good

Seems like BlueZ 5.54 - 5.56 introduced a change in behavior that got fixed in 5.57 - 5.60.

**Comment by N0rbert** [comment] 2021-11-22 13:05
It was a typo. In [previous comment](https://github.com/blueman-project/blueman/issues/1621#issuecomment-974695148) I mean Ubuntu MATE 20.10.

**Comment by cschramm** [comment] 2021-11-22 15:30
That'd bring it down to a change introduced in 5.56. If you're keen you could try 5.55-0ubuntu1.2 on 21.04 to confirm.

**Comment by N0rbert** [comment] 2021-11-22 15:42
Already done at https://github.com/blueman-project/blueman/issues/1621#issuecomment-968338780 .

**Comment by cschramm** [comment] 2021-11-24 13:22
I reread that several times now but can't spot a part about bluez 5.55-0ubuntu1.2 on Ubuntu 21.04. :thinking:

**Comment by N0rbert** [comment] 2021-11-24 18:27
Specially tested 
> bluez 5.55-0ubuntu1.2 on Ubuntu 21.04

↑ it works as expected.

**Comment by cschramm** [comment] 2021-11-25 11:30
Thanks for verifying.

Unfortunately I fail to replicate this with any of my devices but looking at the code I immediately see that it can happen anytime. [`update_found_devices`](https://git.kernel.org/pub/scm/bluetooth/bluez.git/tree/src/adapter.c?h=5.56#n6605), triggered by `MGMT_EV_DEVICE_FOUND`, creates the object and sets initial properties. These changes are collected and translated into D-Bus signals using `g_idle_add`. `Connected: true` and proper `Name` and `Alias` are set in [`connected_callback`](https://git.kernel.org/pub/scm/bluetooth/bluez.git/tree/src/adapter.c?h=5.56#n8775), triggered by `MGMT_EV_DEVICE_CONNECTED`. This might or might not happen before the idle processing and thus might or might not make it into the initial signal. I can imagine that the advertisement monitoring stuff added in 5.56 causes a slight delay somewhere so that we now get two signals instead of one in @N0rbert's case.

**Comment by infirit** [comment] 2021-11-25 16:32
I get this sometimes for far away devices. I'm almost done reworking the devicelist and I handle this case where we hide Noname dvices with Name and Alias updated later. It's just using a ModelFilter is a royal pita. https://github.com/blueman-project/blueman/pull/1634

**Comment by N0rbert** [comment] 2022-01-25 05:40
@github-actions thanks, very friendly.

**Comment by infirit** [comment] 2022-06-15 15:18
The filter rework is doneand merged in master, so as soon as a name shows up the device will be revealed in the list.

**Closed by infirit** 2022-06-15 15:18 UTC
Labels: bug
